# Generated by Django 5.1.3 on 2024-11-26 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=80)),
                ('festival_dates', models.CharField(max_length=80)),
            ],
        ),
    ]
