# Generated by Django 5.1.3 on 2024-11-30 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_festival_festival_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
