# Generated by Django 5.1.4 on 2024-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_festival_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='festival_status',
            field=models.CharField(choices=[('created', 'CREATED'), ('submission', 'SUBMISSION'), ('assignment', 'ASSIGNMENT'), ('review', 'REVIEW'), ('scheduling', 'SCHEDULING'), ('final_submission', 'FINAL_SUBMISSION'), ('decision', 'DECISION'), ('announced', 'ANNOUNCED')], default='created', max_length=20),
        ),
    ]
