# Generated by Django 5.1.3 on 2024-11-26 11:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=80)),
                ('duration', models.FloatField()),
                ('starting_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
