# Generated by Django 5.1.3 on 2024-12-01 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performance_performance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='administrators',
            field=models.ManyToManyField(related_name='performance_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
