# Generated by Django 5.1.3 on 2024-12-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performance_administrators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='created_by',
        ),
    ]
