# Generated by Django 5.1.4 on 2024-12-21 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_alter_festival_festival_status'),
        ('performance', '0008_performance_rating_alter_performance_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='festival.festival'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
