# Generated by Django 5.1.4 on 2025-01-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_performance_festival_alter_performance_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'permissions': [('can_edit_own_or_administered_performance', 'Can edit or delete own or administered performances')]},
        ),
        migrations.AddField(
            model_name='performance',
            name='technical_specs',
            field=models.FileField(blank=True, null=True, upload_to='technical_specs/'),
        ),
    ]
